// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS51nNyoDF2s8LyibApAhc01pK89OHDjY',
    appId: '1:860113358801:web:dcc889f1a2294e0d991af0',
    messagingSenderId: '860113358801',
    projectId: 'taskflow-app-1f89f',
    authDomain: 'taskflow-app-1f89f.firebaseapp.com',
    storageBucket: 'taskflow-app-1f89f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIvQw2DnHx-1OvgxlNQD0nq3FKvnZoZmQ',
    appId: '1:860113358801:android:fe69912fed89933e991af0',
    messagingSenderId: '860113358801',
    projectId: 'taskflow-app-1f89f',
    storageBucket: 'taskflow-app-1f89f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9lnSM74_mNTRrQD5qYCZBeKnEcLwYaHc',
    appId: '1:860113358801:ios:f763714fc504fbce991af0',
    messagingSenderId: '860113358801',
    projectId: 'taskflow-app-1f89f',
    storageBucket: 'taskflow-app-1f89f.firebasestorage.app',
    iosBundleId: 'com.example.taskflowApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9lnSM74_mNTRrQD5qYCZBeKnEcLwYaHc',
    appId: '1:860113358801:ios:f763714fc504fbce991af0',
    messagingSenderId: '860113358801',
    projectId: 'taskflow-app-1f89f',
    storageBucket: 'taskflow-app-1f89f.firebasestorage.app',
    iosBundleId: 'com.example.taskflowApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS51nNyoDF2s8LyibApAhc01pK89OHDjY',
    appId: '1:860113358801:web:2db2a26c2b41dd0d991af0',
    messagingSenderId: '860113358801',
    projectId: 'taskflow-app-1f89f',
    authDomain: 'taskflow-app-1f89f.firebaseapp.com',
    storageBucket: 'taskflow-app-1f89f.firebasestorage.app',
  );
}
